### ISSUE TITLE
How to programmatically changing to next step?

### ISSUE THREAD

**Issue by chaernh** [pokhrelashok/vue-step-progress-indicator#2]
`submit(step) {
	axios.post(link, form, headers).then(res => {
		this.onStepChanged()
	}).catch(err => {
		console.log(err.response.data.message)
	})
},`

### Flow: 
1. Send data to server
2. If success, go to next page

Any solutions?

**Comment by pokhrelashok** [comment]
Use a data variable for `:active-step` prop, something like `activeStep` and then change it on success.
`
submit(step) { axios.post(link, form, headers).then(res => { this.activeStep+=1 }).catch(err => { console.log(err.response.data.message) }) },
`
